"""refactor: update schema (normalize schema constraints and data types)

Revision ID: 88441ba73f78
Revises: f2bf7e845a02
Create Date: 2026-04-21 23:10:05.560941

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88441ba73f78"
down_revision: str | Sequence[str] | None = "f2bf7e845a02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile",
        sa.Column("country_name", sa.VARCHAR(length=128), nullable=True),
    )
    op.alter_column(
        "user_profile",
        "gender",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "user_profile",
        "age_group",
        existing_type=postgresql.ENUM(
            "ADULT",
            "TEENAGER",
            "CHILD",
            "SENIOR",
            name="agegroupenum",
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.execute("DROP TYPE IF EXISTS agegroupenum")
    op.alter_column(
        "user_profile",
        "country_id",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.VARCHAR(length=2),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_user_profile_name"), table_name="user_profile")
    op.create_unique_constraint("uq_user_profile_name", "user_profile", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_profile_name", "user_profile", type_="unique")
    op.create_index(
        op.f("ix_user_profile_name"),
        "user_profile",
        ["name"],
        unique=False,
    )
    op.alter_column(
        "user_profile",
        "country_id",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.VARCHAR(length=3),
        existing_nullable=False,
    )
    op.alter_column(
        "user_profile",
        "gender",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.drop_column("user_profile", "country_name")
    # ### end Alembic commands ###
