"""cleanup: drop sample_size field from user_profile

Revision ID: 2c136e5a99e3
Revises: 88441ba73f78
Create Date: 2026-04-22 04:22:38.562580

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c136e5a99e3"
down_revision: str | Sequence[str] | None = "88441ba73f78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "sample_size")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile",
        sa.Column(
            "sample_size",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###
