"""fix country_id field

Revision ID: c264bf5f157e
Revises: 2d556d0a5e52
Create Date: 2026-04-20 09:08:51.656449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c264bf5f157e'
down_revision: Union[str, Sequence[str], None] = '2d556d0a5e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'gender_probability',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('user_profile', 'country_probability',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'country_probability',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.alter_column('user_profile', 'gender_probability',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
