"""recreate user_profile table

Revision ID: f2bf7e845a02
Revises: c264bf5f157e
Create Date: 2026-04-20 14:00:30.177438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bf7e845a02'
down_revision: Union[str, Sequence[str], None] = 'c264bf5f157e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=32), nullable=False),
    sa.Column('gender_probability', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.INTEGER(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.Enum('ADULT', 'TEENAGER', 'CHILD', 'SENIOR', name='agegroupenum'), nullable=False),
    sa.Column('country_id', sa.VARCHAR(length=3), nullable=False),
    sa.Column('country_probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_index(op.f('ix_user_profile_name'), 'user_profile', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_name'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
